---
title: "Map of Houston"
format: gfm
editor: visual
---

```{r}
#install.packages('terra')
#install.packages('tidyverse')
#install.packages('ggmap')
install.packages("knitr")

library('tidyverse')
library('ggmap')
library('terra')
library('maptiles')

```

```{r}
power_plants <- read.csv('Untitled spreadsheet - Sheet1.csv')


register_google(key = "AIzaSyBwB1vPbEGg11mc-E2ePo8K_C5-cSmsWPw", write = TRUE)
```

```{r}
power_plants_addr <- data.frame(Address = power_plants$Address,
                   stringsAsFactors = FALSE)

power_plant.geo <- mutate_geocode(power_plants_addr, location = Address, output = "latlona")
```

```{r}
stations <- read.csv('Houston Data Collection - Charlotte.csv')


register_google(key = "AIzaSyBwB1vPbEGg11mc-E2ePo8K_C5-cSmsWPw", write = TRUE)

```

```{r}
stations_addr <- data.frame(Address = stations$Address,
                   stringsAsFactors = FALSE)

stations_addr.geo <- mutate_geocode(stations_addr, location = Address, output = "latlona")


```

```{r}
ext_lon <- c(-95.231449, -95.450936, -95.219529)
ext_lat <- c(29.718620, 29.645589, 29.821974)


pow_pla_lon <- c(power_plant.geo$lon, ext_lon)
pow_pla_lat <- c(power_plant.geo$lat,ext_lat)
pow_pla_lonlat <- cbind(pow_pla_lon,pow_pla_lat)

pow_pla_pts <- vect(pow_pla_lonlat, crs = crdref)

```

```{r}
r<-terra::vect("tl_2021_txharris_roads/tl_2021_48201_roads.shp")

rdf<-as.data.frame(r)

tsp<-subset(r, r$FULLNAME=="N Loop W Svc Rd" | r$FULLNAME == "Southwest Fwy" | r$FULLNAME == "Katy Fwy" | r$FULLNAME == "S Loop W Svc Rd" | r$FULLNAME == "W Loop S Fwy" | r$FULLNAME == "W Loop S Svc Rd" | r$FULLNAME == "Gulf Fwy" | r$FULLNAME == "North Fwy" | r$FULLNAME == "N Loop E Fwy" | r$FULLNAME == "N Loop E Svc Rd" | r$FULLNAME == "South Fwy")
tsp_df <- as.data.frame(tsp)
terra::plot(tsp)
```

```{r}
sta_lon <- stations_addr.geo$lon
sta_lat <- stations_addr.geo$lat
sta_lonlat <- cbind(sta_lon,sta_lat)

crdref <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"

sta_pts <- vect(sta_lonlat, crs = crdref)

```

```{r}
df <- stations_addr.geo %>%
  filter(Address == "3604 Main St., Houston, TX 77002") %>%
  select(lon,lat)
x <- vect(df, geom = c('lon','lat'), crs = crdref)
extent <- buffer(x, width = 10000)

buff_sta <- buffer(sta_pts, width = 250)
outfile <- "buff_sta.shp"
writeVector(buff_sta, outfile, overwrite = TRUE)
#bg <- get_tiles(ext(extent))
#plot(bg)
plot(sta_pts)
points(pow_pla_pts, col = 'blue')
lines(tsp, col = 'yellow', lwd = 2)
lines(buff_sta, col = 'red')
```
